* Week 1 - Globalization
** Introduction
*** Globalization - increasing ties of global integration - Little G - globalization
*** Studying how little 'G' globalization is used to tell a story of global market flattening - Big G globalization.
*** We're constantly worrying about market forces, about whether our investment will yield good results, about whether we should invest in the first place. Globalization has increased the influence of market forces in our personal lives.
*** Globalization is bound up with Neoliberalism - Letting market forces shape governement policies, thereby shape personal lives.
*** It makes it seem inevitable that we need to run our lives according to a certain sort of market logic sometimes.
*** And that's really important to grasp at the same time as we grasp the actual real world interconnections of globalization.
*** Now, key to doing that, is making sense of what is called Neoliberalism.
*** Global trade of commodities is basically the core, the driving force of global integration.
*** But we also, in doing so, explore big debate that goes on about whether it is unhealthier to be wealthier. Some economists argue that to be wealthy is to be healthy. Not necessary based on countries like CRC, NZ etc., which have low per-capita income but as much if not a higher life-expectancy rate than the US, Norway or Japan.
*** How to respond to Globalization?
**** Reaction - Right-wing.
**** Resistance - Left-wing.
**** Resilience - Middle ground.
*** We are interested in how market forces are shaping our personal lives and helping you to make sense of how your own personal calculations and, and decisions are shaped by market forces. In turn, that enables us to look at how our personal lives, very localized personal lives, are being caught up in global market changes. Market-led changes and changes that are, in a sense, for the market and lead to kinds of government by the market and for the market.  I'm interested in how that works at a personal level.
** What is Globalization?
*** Globalization is two things. It's the extension, intensification, and acceleration of consequential worldwide interconnections. And at the same time, it's a big buzzword. A big buzzword of political speech that's used by business leaders, by political leaders, by protestors, in different ways but nevertheless, used as a buzzword to make politically charged arguments about how the world is shaping up and where it should be headed.
*** Interconnection in terms of trade ties, global finance and money flows, law-making through trade-agreements, and human rights law-making.
*** Economists look at the finance and money flow aspect of Globalization.
*** Political Scientists look how the function of the nation-state has changed due to Globalization.
*** Geographers look at how it is affecting the ground. How the actual geography at the ground level is gradually shifting due to global interconnections.
*** Historians focus on national history and cultural history, but not their interconnections.
*** We have to go beyond all this and look at how all these disciplines are affected by Globalization.
** How are we affected by Globalization?
*** The global capitalist system has produced a very uneven playing field.
*** Behing the Beautiful Forevers - Katherine Boo - Life, death and hope in a Mumbai undercity.
**** *Abdul and his neighbors were squatting on land that belonged to the airports authority of India. Only a coconut tree-lined thoroughfare separated the slum from the entrance to the international terminal. Serving the airport clientele and encircling Annawadi, were 5 extravagant hotels. Everything around is roses is how Abdul's younger brother Mirchi put it. And we're the shit in between. Inside was carbon black, frantic with rats, and yet relieving. Abdul's storeroom, 120 square feet, piled high to a leaky roof with the things in this world he knew how to handle. Empty wallets and whiskey bottles, umbrellas stripped to the ribs by monsoons, broken shoelaces, yellowed Q-tips, snarled cassette tape, torn plastic casings that once held imitation Barbies. Somewhere in the darkness, there was a Barbee or Barblie herself, maimed in one of the experiments to which children who had many toys seemed to subject those toys no longer favored. Abdul had become expert over the years at minimizing distraction. He placed all such dolls in his trash pile tits down.*
**** Michel Foucalt - Market Governmentality.
***** People get enlisted as - Calculating, enterprising, accountable, risk-manaing, subjects. Neoliberal responsibilization. We become entrepreneurs of ourselves.
*** ABC of Market Relations.
**** A - Advertising.
**** B - Business. What's best for business is also good for us individuals.
**** C - Consumerism.
***** Flipside of this is the credit that we have to borrow, which leads to debt.
**** D - Debt. Personal discipline and despair. It shapes us in profoundly unequal ways.
***** Foreclosure of homes during recessio is a very personal experience of market relations.
**** E - Education for entrepreneurialism. MOOCs among many things that will be discussed.
*** Gillian Tett - Fool's Gold - How unrestrained greed corrupted a dream. Shattered global markets. And unleashed a catastrophe.
**** *On January 29th, 2009, J.P. Morgan Chase hosted a cocktail party for 200 of its key clients and contacts in the elegant surroundings of the Piano Bar, in the smart Swiss ski resort of Davos. The occasion was the much buzzed about annual gathering of the World Economic Forum, which for the first seven years of the decade had been dominated by the investment banking elite, extolling the virtues of free markets, globalization, and financial innovation. Sleek black limousines whisked them between meetings at hotels in close proximity; they were too grand to trudge through snowy slush. But this year a funereal mood hung in the crisp mountain air. Almost no banking CEOs attended. John Thain, the former CEO of Merrill Lynch, had been scheduled to host a breakfast but had just been sacked. Bob Diamond, head of Barclay's, cancelled his dinner appearance at short notice because his bank share price was collapsing. Lloyd Blankfein, head of Goldan Sachs, stayed away as a demonstration of cost-cutting. As the American and European public realized the scale of the banks' woes over the winter, and the level of government, read taxpayer, money being used to prop them up, outrage was escalating.*
